import argparse
import os.path as osp
this_dir = osp.dirname(__file__)

def parse_sgnet_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--data_root', default='E:\\Datasets\\PIE', type=str)
    parser.add_argument('--checkpoint', default='', type=str)
    parser.add_argument('--start_epoch', default=1, type=int)
    parser.add_argument('--gpu', default='0', type=str)
    parser.add_argument('--num_workers', default=0, type=int)
    parser.add_argument('--epochs', default=200, type=int)
    parser.add_argument('--batch_size', default=128, type=int)
    parser.add_argument('--weight_decay', default=0, type=float)
    parser.add_argument('--seed', default=1, type=int)
    parser.add_argument('--shuffle', default=True, type=bool)
    parser.add_argument('--dataset', default='PIE', type=str)
    parser.add_argument('--lr', default=5e-04, type=float)
    parser.add_argument('--model', default='SGNet', type=str)
    parser.add_argument('--bbox_type', default='cxcywh', type=str)
    parser.add_argument('--normalize', default='zero-one', type=str)
    parser.add_argument('--hidden_size_traj', default=256, type=int)
    parser.add_argument('--hidden_size_sp', default=128, type=int)
    parser.add_argument('--enc_steps', default=15, type=int)
    parser.add_argument('--dec_steps', default=45, type=int)
    parser.add_argument('--dropout', default=0.1, type=float)
    parser.add_argument('--FPS', default=30, type=int)
    parser.add_argument('--min_bbox', default=[0,0,0,0], type=list)
    parser.add_argument('--max_bbox', default=[1920, 1080, 1920, 1080], type=list)
    parser.add_argument('--loc_dim', default=4, type=int)
    parser.add_argument('--sp_dim', default=1, type=int)
    parser.add_argument('--d_k', default=32, type=int)
    parser.add_argument('--d_v', default=32, type=int)
    parser.add_argument('--d_inner', default=1024, type=int)
    parser.add_argument('--d_model_traj', default=256, type=int)
    parser.add_argument('--d_model_sp', default=128, type=int)
    parser.add_argument('--n_head', default=16, type=int)
    parser.add_argument('--version_name', required=False, type=str, default='debug')
    parser.add_argument('--patience', default=10, type=int)


    return parser.parse_args()